server: 
    # 服务端口
    port: 8888
    # 服务路径
    contextPath:

spring:
    # 服务名称
    application:
        name: SpringWebDemo
    # 服务当前使用的profile
    profiles:
        active: @spring.profiles.active@
    jackson:
        # json中日期是否用timestamps格式交互
        serialization.write-dates-as-timestamps: true
        # json中遇到无效变量是否报错
        deserialization.FAIL_ON_UNKNOWN_PROPERTIES: off
    # 国际化
    messages: 
        basename: i18n/messages
#     # 数据库相关设置
#    datasource:
#        driver-class-name: @datasource.driver@
#        url: @datasource.url@
#        username: @datasource.username@
#        password: @datasource.password@
#        test-while-idle: true
#        max-wait-millis: 30000
#        validation-query: 'SELECT 1'
#        time-between-eviction-runs-millis: 20000
#        min-evictable-idle-time-millis: 28700
    # JPA相关设置
#    jpa:
##        database-platform: @datasource.dialect@
#        hibernate.ddl-auto: @datasource.jpa.hibernate.ddl-auto@
#        show-sql: @datasource.jpa.show-sql@
    # mongodb相关设置
#    data:
#        mongodb:
#            host: "@spring.data.mongodb.host@"
#            port: "@spring.data.mongodb.port@"
#            database: "@spring.data.mongodb.database@"
#            username: "@spring.data.mongodb.username@"
#            password: "@spring.data.mongodb.password@"


# LOG相关设置
logging:
  path: /var/log/SpringWebDemo
  level:
    com.liuw.spring: TRACE
    org.springframework: WARN

test.repeat.times: 5
test.repeat.times2: 6